addons:
  ssh_known_hosts: russellhay.com
  apt:
    update: true
language: go
go:
- 1.10.x
install: go get -u -v github.com/spf13/hugo
script:
- mkdir -p themes/pic3/static/css/
- make
- hugo
before_install:
- openssl aes-256-cbc -K $encrypted_44f97fad52ae_key -iv $encrypted_44f97fad52ae_iv
  -in deploy.rsa.enc -out deploy.rsa -d
- sudo apt-get update
- sudo apt-get install -y ruby-sass
notifications:
  email:
    on_faliure: always
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy.rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy.rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/poorimpulse/
  on:
    branch: master